version: '3'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: depressionDB
      POSTGRES_USER: depressionhub
      POSTGRES_PASSWORD: depressionhub123
    ports:
      - 5432:5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: